name: Build RustDesk Windows Client

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Replace server config
      shell: bash
      run: |
        CONFIG_FILE="rustdesk/src/common/config.rs"
        sed -i 's/public\\.rustdesk\\.com:21115/185.255.208.35:21115/g' $CONFIG_FILE
        sed -i 's/public\\.rustdesk\\.com:21116/18
