name: Build RustDesk Windows Client

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install vcpkg and opus
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://github.com/microsoft/vcpkg/archive/refs/heads/master.zip -OutFile vcpkg.zip
        Expand-Archive vcpkg.zip -DestinationPath .
        .\vcpkg-master\bootstrap-vcpkg.bat
        .\vcpkg-master\vcpkg.exe install opus:x64-windows-static --classic
      working-directory: ${{ github.workspace }}

    - name: Set VCPKG_ROOT environment variable
      run: echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg-master"_
